SELECT * FROM payment WHERE amount > 10 ORDER BY amount ASC;

-- RETO WHERE: 
-- EL MANAGER DE INVENTARIO REQUIERE SABER CUANTAS PELICULAS RENTADAS NO HAN SIDO REGRESADAS
-- AÚN (return_date is null)
SELECT COUNT(*) FROM rental WHERE return_date IS NULL;

-- 
--EL MANAGER DE VENTAS REQUIERE UNA LISTA DE TODOS LOS payment_ids CON UNA CANTIDAD/IMPORTE
--MENORES O IGUALES A $2. INCLUYA EL payment_id Y amount 

SELECT payment_id,amount FROM payment WHERE amount<= 2 ORDER BY amount ASC;